export default {
  fontWeight: {
    normal: 400,
    bold: 600,
    xbold: 700,
  },
  fontSizes: {
    xxsmall: "1.0rem",
    xsmall: "1.2rem",
    small: "1.4rem",
    medium: "1.6rem",
    large: "1.8rem",
    xlarge: "2rem",
    xxlarge: "2.2rem",
    extraLarge: "2.4rem",
  },
  zIndex: {
    base: 1,
    secondLayer: 2,
    thirdLayer: 3,
    fourthLayer: 4,
  },
  border: {
    large: "2rem",
    medium: "1rem",
    default: "0.5rem",
  },
  spacings: {
    xxxsmall: "0.5rem",
    xxsmall: "1rem",
    xsmall: "1.5rem",
    small: "2rem",
    medium: "2.5rem",
    large: "3rem",
    xLarge: "3.5rem",
    xxLarge: "4rem",
    xxxLarge: "5rem",
    huge: "6rem",
  },
  colors: {
    gray: "#666",
    white: "#fff",
    black: "#000",
    lynch: "#627D9A",
    indigo: "#3F73CA",
    tussock: "#CB9E49",
    waterloo: "#7e8397",
    aquaHaze: "#f2f5f8",
    regalBlue: "#03366A",
    pictonBlue: "#2ea3f2",
    midnightBlue: "#013668",
  },
} as const;
